const weddingDate = new Date(2025, 4, 11);
const today = new Date();
const msPerDay = 1000 * 60 * 60 * 24;
const daysSinceWedding = Math.floor((today - weddingDate) / msPerDay) + 1;

document.getElementById("dayCount").innerText =
    `Ez a ${daysSinceWedding}. nap az esküvőtök óta.`;


const quotes = [
    { text: `Nem kell megértenünk a világot; elég, ha eligazodunk benne.`, author: `Albert Einstein` },
    { text: 'Még az eleve elrendeltetés hívei is, akik azt állítják, hogy semmit sem tehetünk ellene, szétnéznek, mielőtt átmennek az úttesten.', author: 'Stephen Hawking'},
    { text: `Nincs csapás szörnyűbb, mint amit ember önmagára mér.`, author: `Szophoklész` },
    { text: `Ki tudja, mit hoz a holnap. Olykor épp a felkelő nap hozza a tanácsot.`, author: `A két torony, 2. fejezet` },
    { text: `Általában tanácsosabb, ha azzal mutatja ki eszét az ember, amit elhallgat, mint azzal, amit elmond.`, author: `Arthur Schopenhauer` },
    { text: `A muzulmánok minden keresztény vallást babonasággal vádolnak, mások viszont őket mondják babonásnak. Ki lehet bíró ebben a nagy pörben? Maga az értelem? De hiszen valamennyi felekezet azt állítja, hogy az értelem az ő oldalán áll. Így hát az erő bíráskodik, s ez így lesz mindaddig, míg az értelem elegendő számú koponyát át nem hat, és le nem fegyverezi az erőt.`, author: `Voltaire` },
    { text: 'A föld, ha táplál, mindenütt hazánk lehet.', author: 'Euripidész'},
    { text: `A bátorságot nem lehet hamisítani, olyan erény, amely nem ismer képmutatást.`, author: `Bonaparte Napóleon` },
    { text: `Az optimista egyáltalán nem az, aki soha nem szenvedett, hanem az, aki átélte és legyőzte a kétségbeesést.`, author: `Alekszandr Nyikolajevics Szkrjabin` },
    { text: `Még azt sem tudjuk a halálról, hogy vajon nem a legnagyobb jó-e, mégis úgy félünk tőle, mintha biztosan tudnánk, hogy a legnagyobb rossz.`, author: `Platón` },
    { text: `Egyik ember szülészt keres gondolatai számára, a másik valakit, akinek segíthet - így keletkezik a jó beszélgetés.`, author: `Friedrich Nietzsche` },
    { text: `Jó dolog gazdagnak lenni, és jó dolog erősnek lenni, de sokkal jobb dolog, amikor sok barátja van az embernek.`, author: `Euripidész` },
    { text: `Az élet olyan, mint a biciklizés. Ha meg akarod tartani az egyensúlyt, mozgásban kell maradnod.`, author: `Albert Einstein` },
    { text: `Óvakodj az orvosi könyvektől, belehalhatsz egy nyomdahibába.`, author: `Mark Twain` },
    { text: `Ha igazad van, megengedheted magadnak, hogy megőrizd a nyugalmad. Ha nincs igazad, nem engedheted meg, hogy elveszítsd.`, author: `Gandhi` },
    { text: `A fájdalom is csupán hangulat. Néha meglepi az embert, aztán távozik.`, author: `Boncza Berta` },
    { text: `Ha barát kell, a legjobb leszek. Ha magányra vágysz, én a csönd leszek. Es ember leszek, mert emberre vágysz: ki szeret, ki elfogad, s kit igaznak látsz.`, author: `Charles Dickens` },
    { text: `Az a szív, mely sokat szeret, sokat szenved.`, author: `Dosztojevszkij` },
    { text: `A szerelem mindent pótol, s a szerelmet\nNem pótolja semmi.`, author: `Petőfi Sándor` },
    { text: `A sors - minden kegyetlensége mellett - gondol néha ránk.`, author: `Ady Endre` },
    { text: `A legnagyobb hiba, amit az orvosok elkövetnek, hogy a testet anélkül próbálják meggyógyítani, hogy az elmét is gyógyítani próbálnák. Pedig az elme és a test egy, és nem szabadna külön kezelni.`, author: `Platón` },
    { text: `Egy embert szeretni azt jelenti, hogy olyannak látjuk, amilyennek Isten gondolta.`, author: `Dosztojevszkij` },
    { text: `A szeretet és az igazság olyan szoros egységet alkot, hogy gyakorlatilag nem is lehet őket szétválasztani. Olyanok, mint ugyanannak az éremnek két oldala.`, author: `Gandhi` },
    { text: `Valahogy csak lesz, mert úgy még sohasem volt, hogy sehogy sem lett volna.`, author: `Babits Mihály` },
    { text: `Nem az számít, hogy minek születik valaki, hanem az, hogy mivé nő fel.`, author: `Joanne Kathleen Rowling` },
    { text: `Mindenki elérhet valamit, ha kellő erővel próbálkozik.`, author: `Stephen Hawking` },
    { text: `Akármilyen sok időt töltesz is valakivel, a végén úgy érzed majd, hogy nem voltál eleget vele.`, author: `Stephen King` },
    { text: `A kérdés, ami néha elbizonytalanít: én vagyok őrült, vagy mindenki más?`, author: `Albert Einstein` },
    { text: `Sok van, mi csodálatos, De az embernél nincs semmi csodálatosabb.`, author: `Szophoklész` },
    { text: `Nem mi döntjük el, hogy mikor éljünk. Mi csak abban dönthetünk, hogy mi a teendő, ha már itt vagyunk.`, author: `Gyűrűk ura` },
    { text: `Bármit teszel, jelentéktelen lesz, de nagyon fontos, hogy megtedd.`, author: `Gandhi` },
    { text: `Akinek van miért élnie, szinte minden hogyant ki tud bírni.`, author: `Friedrich Nietzsche` },
    { text: `Ne sikeres ember próbálj lenni, hanem értékes!`, author: `Albert Einstein` },
    { text: `A teljesületlen kívánság okozta kín kicsiny ahhoz képest, amelyet a megbánás okoz: mert amaz a mindig kérdéses, beláthatatlan jövő előtt áll, emez a visszavonhatatlanul lezárt múlt előtt.`, author: `Arthur Schopenhauer` },
    { text: `Ha nem tehetsz nagy dolgokat, tégy apró dolgokat nagyszerű módon!`, author: `Martin Luther King` },
    { text: `Meghalnánk, mondván:\n'Bűn és szenny az élet,\nKetten voltunk csak tiszták, hófehérek.'`, author: `Ady Endre` },
    { text: `Az emberi hang sosem ér olyan messzire, mint a lelkiismeret.`, author: `Gandhi` },
    { text: `Felfedezni valamit annyit tesz, mint látni, amit mindenki lát, és közben arra gondolni, amire még senki.`, author: `Arthur Schopenhauer` },
    { text: `Az összevisszaságban találd meg az egyszerűséget, a hangzavarban a harmóniát. A nehézségek közt mindig ott van a lehetőség.`, author: `Albert Einstein` },
    { text: `Sose halaszd holnapra, amit holnapután is megtehetsz.`, author: `Mark Twain` },
    { text: `Az esküszó erőt önt a megreszkető szívbe.`, author: `A Gyűrű szövetsége, 425. oldal` },
    { text: `Nem kell mindenre odafigyelni, amit hall az ember.`, author: `A gyűrű szövetsége, 34. oldal` },
    { text: `Ne mondj le semmiről. Minden lemondás\negy kis halál. Ne mondj le semmiről.`, author: `Babits Mihály` },
    { text: `Csak akkor születtek nagy dolgok,\nHa bátrak voltak, akik mertek.`, author: `Ady Endre` },
    { text: `Ha az ember megszeret valakit, (...) egészen soha nem gyógyulhat ki belőle.`, author: `Stephen King` },
    { text: `A legjobb jós a belátás s józan értelem.`, author: `Euripidész` },
    { text: `A gravitáció nem hibáztatható azért, hogy az emberek szerelembe esnek.`, author: `Albert Einstein` },
    { text: '- Mit szeret Norbi? Mit szeret Norbi?\n- ...\nÁgi és Orsi teljesen egyszerre.\n- Csengét!\n- A Gyűrűk urát!', author: 'Idézet az életből'},
    { text: `A gravitáció magyarázatot ad a bolygók mozgására, de nem válaszol arra a kérdésre, hogy ki hozta mozgásba azokat.`, author: `Isaac Newton` },
    { text: `Ha tükröt tartasz mások elé, ne felejts magad is tükörbe pillantani`, author: `Platón` },
    { text: `Tégy, ahogy jónak látod, úgyis megbánod, bárhogyan cselekszel.`, author: `Szókratész` },
    { text: `Ezt sírja: élni, élni még!\nMert élni, jaj, sohsem elég!\nAz élet örök táruló:\nAki nem éli, áruló!`, author: `Tóth Árpád` },
    { text: `Jól csak a szívével lát az ember. Ami igazán lényeges, az a szemnek láthatatlan.`, author: `Antoine de Saint-Exupéry: A kis herceg` },
    { text: `Add meg minden napnak az esélyt, hogy életed legszebb napja legyen!`, author: `Mark Twain` },
    { text: `Ne törődj semmivel, ne nézz se előre, se hátra, ne légy kíváncsi, mennyit végeztél és mennyi van még hátra. Csak dolgozzál, s meglesz minden idején.`, author: `Lev Tolsztoj` },
    { text: `Tanulj a tegnapból, élj a mának és reménykedj a holnapban. A legfontosabb azonban, hogy ne hagyd abba a kérdezést`, author: `Albert Einstein` },
    { text: `Néha az igazi szeretet éppen olyan néma, mint amilyen vak.`, author: `Stephen King` },
    { text: `Körülöttetek pedig ott a nagyvilág; bezárkózni, azt lehet,\nde a világot örökre kizárni azt már nem.`, author: `Gyűrűk ura, Prológus, 3. fejezet` },
    { text: `Galileit elítélték, és a föld mégis mozgott tovább.`, author: `Juhász Gyula` },
    { text: `Mily öröm énnekem hogy öröm vagyok én neked.`, author: `Babits Mihály` },
    { text: `Ha sokáig pillantasz a mélységbe, a mélység is beléd pillant.`, author: `Friedrich Nietzsche` },
    { text: `A jelen soha ki nem elégít; a jövendő pedig bizonytalan, és a múlt visszahozhatatlan.`, author: `Arthur Schopenhauer` },
    { text: `Ha nem tudsz repülni, hát fuss. Ha nem tudsz futni, hát gyalogolj. Ha nem tudsz járni, hát mássz. Bármit is teszel, nem állhatsz meg: menned kell az utadon előre.`, author: `Martin Luther King` },
    { text: `Az optimizmus (...) semmi más, sajnos (...), mint annak a dühös bizonygatása, hogy minden a legeslegjobb, mikor minden a legrosszabb.`, author: `Voltaire` },
    { text: `Egyesek Einsteint vádolták az atombomba létrehozása miatt, minthogy ő fedezte fel a tömeg és az energia közötti kapcsolatot. Olyan ez, mintha Newtont okolnánk a repülőgépek lezuhanása miatt, hiszen ő fedezte fel a gravitáció törvényét.`, author: `Stephen Hawking` },
    { text: `Vajon olcsó álmokkal és üres hazugságokkal áltatjuk-e magunkat akkor, amidőn azt képzeljük, hogy léteznek az istenek, pedig csak a vak véletlen és a vad változás mozgatja a világot?`, author: `Euripidész` },
    { text: `Ahol élet van, ott remény is van.`, author: `Gyűrűk ura` },
    { text: `A vizsgálódás nélküli élet nem embernek való élet.`, author: `Szókratész` },
    { text: `A különbség a között, amit megteszünk és amire képesek lennénk, megváltoztathatná a világot.`, author: `Gandhi` },
    { text: `Mindig azt hajtogatják, milyen nagy bölcsek voltak a régiek, az őseink, de énszerintem nem tudtak azok semmit: kitaláltak szebbnél szebb dalokat az ünnepekre, lakomákra, mikor úgyis örül az ember, bezzeg azt nem bírták kifundálni, hogyan lehetne dallal meg lantpengetéssel meggyógyítani azt, aki bánatában őrjöng.`, author: `Euripidész` },
    { text: `Minden jól van, minden jóra fordul, minden a lehető legjobban van ezen a legeslegjobb világon.`, author: `Voltaire` },
    { text: `A jövőnek sok neve van: a gyenge úgy hívja, elérhetetlen, a gyáva úgy, ismeretlen, a bátor lehetőségnek nevezi.`, author: `Victor Hugo` },
    { text: `Vannak, akik előre szeretnék tudni, mi kerül az asztalra; de akik a lakomát készítik, inkább titokban tartják: mert a csodálkozás hangosabbá teszi a dicsérő szavakat.`, author: `A király visszatér, 6. könyv, 5. fejezet, 299. oldal` },
    { text: `Ellenzem az erőszakot, mert ha úgy tűnik is, hogy hasznos, a haszon csak átmeneti, de a szörnyűség, amit okoz, maradandó.`, author: `Gandhi` },
    { text: `A legfontosabb dolgokat a legnehezebb elmondani. Ha ezekről beszélsz, nevetségesnek érzed magad, hiszen szavakba öntve összezsugorodnak - amíg a fejedben vannak, határtalannak tűnnek, de kimondva jelentéktelenné válnak. Ám azt hiszem, többről van itt szó. A legfontosabb dolgok túl közel lapulnak ahhoz a helyhez, ahol a lelked legféltettebb titkai vannak eltemetve, irányjelzőkként vezetnek a kincshez, amit az ellenségeid oly szívesen lopnának el. S ha mégis megpróbálsz beszélni róluk, a hallgatóságtól csak furcsálló tekinteteket kapsz cserébe, egyáltalán nem értenek meg, nem értik, miért olyan fontos ez neked, hogy közben majdnem sírva fakadsz. És szerintem ez a legrosszabb. Amikor a titok nem miattad marad titok, hanem mert nincs, aki megértsen.`, author: `Stephen King` },
    { text: `Sokkal jobb, ha az ember pont olyan, mint mindenki más. Ami engem illet, örülök, ha öregkoromra fedél van a fejem fölött, még ha lehetne se akarnék király vagy tudom is én, mi lenni. Legjobb szerintem az arany középút, a tapasztalat azt mutatja, az használ legtöbbet az embereknek.`, author: `Euripidész` },
    { text: `Ha az életben elérhető sikert A-nak vesszük, akkor A=X+Y+Z. X a munka, Y a játék, Z pedig, hogy befogod a szád.`, author: `Albert Einstein` },
    { text: `Nem lenne nagy dolog az univerzum, ha nem olyan embereknek adna otthont, akiket szeretsz.`, author: `Stephen Hawking` },
    { text: `Az élet piszkos, csak a semmi tiszta.`, author: `Babits Mihály` },
    { text: `Szelídséggel az egész világot felforgathatod.`, author: `Mahatma Gandhi` },
    { text: `Ha szeretünk valakit, nem sokáig emlékszünk arra, hogy megbántott bennünket.`, author: `Dosztojevszkij` },
    { text: `Az emberiséget a szeretet törvénye uralja. Ha az erőszak, azaz a gyűlölet uralkodna, már rég kihaltunk volna. És mégis a tragédiája a dolognak, hogy az úgynevezett civilizált emberek és nemzetek úgy viselkednek, mintha a társadalom alapja az erőszak lenne.`, author: `Gandhi` },
    { text: `Nem vagyok különösebben tehetséges, csak szenvedélyesen kíváncsi.`, author: `Albert Einstein` },
    { text: `Egy pesszimista minden lehetőségben látja a nehézséget; egy optimista minden nehézségben meglátja a lehetőséget.`, author: `Winston Churchill` },
    { text: `Van-e korlát, melyen a szeretet nem tör át?`, author: `Gandhi` },
    { text: `Legnagyobb cél pedig, itt, e földi létben,\nEmber lenni mindég, minden körülményben`, author: `Arany János` },
    { text: `Az időnek egyetlen oka van: minden nem történhet egyszerre.`, author: `Albert Einstein` },
    { text: `Vannak olyan emberek (...), akik sohasem ismerik el, hogy hibáztak, és mindig újabb, gyakran egymásnak is ellentmondó érvekkel jönnek elő, melyekkel azt bizonygatják, hogy igazuk van. Mások azt állítják, hogy sohasem támogatták igazán a hibás nézetet, vagy ha igen, akkor csak azért tették, hogy megmutassák ellentmondásait. Számos példát hozhatnék fel, de nem teszem, mivel túlságosan népszerűtlen lennék. Azt hiszem, sokkal jobb és kevésbé zavarba ejtő, ha leírom, hogy hibáztam.`, author: `Stephen Hawking` },
    { text: `Röviden és homályosan fogalmazzatok.`, author: `Bonaparte Napóleon` },
    { text: `Valóban tudom, mily gonosz, mit tenni szándékozom, de erősebb bármely megbánásnál a haragom. A harag, amely a halandókra a legtöbb gonoszt szabadítja.`, author: `Euripidész` },
    { text: `Megtanultam, hogy várni a legnehezebb, és szeretnék hozzászokni, tudni, hogy velem vagy akkor is, ha nem vagy mellettem.`, author: `Paulo Coelho` },
    { text: `A szerelem az emberi nem magasztos vigasztalója, a világ fennkölt megtartója, érzékeny lelkek öröme, igen, a gyenge szerelem.`, author: `Voltaire` },
    { text: `Olyan mindegy, hogy ki az ellenség, ha a támadását nem tudjuk visszaverni.`, author: `Gyűrűk ura` },
    { text: `Van egyfajta rabló, akit a törvény nem büntet, és aki a legértékesebbet rabolja el az embertől: az időt.`, author: `Bonaparte Napóleon` },
    { text: `A vallások különböző utak, amelyek ugyanoda vezetnek. Mit számít, hogy külön úton járunk, ha a célunk közös?`, author: `Gandhi` },
    { text: `Be balgák vagytok, óh halandók, akik azt Mondjátok, hogy van sors és vannak Istenek, Hisz ha van sors, szükség istenekre nincs, S az Istenek, ha erősek, a sors semmi se.`, author: `Euripidész` },
    { text: `Bizonyos dolgokat jobb nem látni és nem hallani, csak amikor már vége.`, author: `Stephen King` },
    { text: `Az, hogy fájdalmat érzünk, éppoly természetes, mint hogy levegőt veszünk`, author: `Joanne Kathleen Rowling` },
    { text: `Az embernek ahhoz, hogy boldog legyen, két dolgot kell tennie: először hinnie kell, hogy van az életének értelme. Másodszor meg kell találnia, hogy mi az.`, author: `Lev Tolsztoj` },
    { text: `Az okos emberek megoldják a problémákat, a zsenik pedig megelőzik őket.`, author: `Albert Einstein` },
    { text: `Húsz év múlva sokkal jobban fogod sajnálni azokat a dolgokat, amiket nem csináltál meg, mint azokat, amiket igen.`, author: `Mark Twain` },
    { text: `Élj úgy, mintha ma lenne az utolsó napod. Tanulj úgy, mintha örökké élnél.`, author: `Gandhi` },
    { text: `- Hogyan imádják az Istent Eldorádóban?\n- Sehogysem imádjuk (...), nincs mit kérni tőle, mindennel elárasztott, amire szükségünk van; folytonosan köszönetet mondunk neki.`, author: `Voltaire` },
    { text: `Még ha fel is fedeznek a jövőben valamilyen más elméletet, akkor sem hiszem, hogy az időutazás bármikor is megvalósulhat. Ha megvalósulhatna, akkor mostanra már elözönlöttek volna bennünket a jövőből érkezett turisták.`, author: `Stephen Hawking` },
    { text: `Úgy látszik (...), hogy az emberek megrontották a természetet, mert nem születtek farkasoknak, és lám, mégis farkasok lettek. Az Úristen nem adott nékik huszonnégy fontos ágyúkat, se szuronyokat, s mégis csináltak maguknak ágyúkat és szuronyokat, csak hogy elpusztítsák egymást.`, author: `Voltaire` },
    { text: `Régi bajon nem kell új könnyet ontani.`, author: `Euripidész` },
    { text: `A döntéseinkben, nem pedig a képességeinkben mutatkozik meg, hogy kik is vagyunk valójában.`, author: `Joanne Kathleen Rowling` },
    { text: `Nem vehetik el az önbecsülésünket, ha mi nem adjuk oda.`, author: `Gandhi` },
    { text: `Kevesen látják, hova viszi őket az útjuk, amíg a végére nem érnek.`, author: `Gyűrűk ura` },
    { text: `Az embernek azon az úton kell elindulnia, amelyre a szükség kényszeríti.`, author: `Gyűrűk ura` },
    { text: `A szeretet lángjaiban a legkeményebb vasnak is  meg kell olvadnia.`, author: `Gandhi` },
    { text: `S ahogy ott állt a sötétben, a sötétnél is sötétebb kétségbeeséssel és haraggal a szívében, egyszerre mintha fényt látott volna: fényt az agyában, kezdetben szinte elviselhetetlenül ragyogó fényt, olyat, mint amilyennek a napsugarat látja, aki hosszú ideig bujkált ablaktalan zugban.`, author: `Gyűrűk ura` },
    { text: `Sosem tudhatod, milyen eredményei lesznek a cselekedeteidnek, de ha nem cselekszel, eredményük sem lesz.`, author: `Gandhi` },
    { text: `Együtt lehet élni a félelemmel (...). Talán nem örökké, de mindenesetre jó sokáig. A sértés az, amivel együtt élni lehetetlen, mert a sértés léket vág a gondolatokba, és ha belenéztek, azt látjátok, hogy ott mélyen élő dolgok mozognak, kicsi sárga szemük van, amely sohasem pislog, és irtózatos bűz tapasztja össze a sötétséget, aztán az ember egyszerre úgy érzi, talán egy egész világegyetemet találni odalenn, ahol négyszögletes hold függ az égen, hideg hangon nevetnek a csillagok, néhány háromszögnek négy oldala van, a maradéknak meg öt vagy éppenséggel öt az ötödik hatványon.`, author: `Stephen King` },
    { text: `Néha, amikor rosszul mennek a dolgok, több segítséget kapunk, mint amire számítunk. És néha még ez sem elég.`, author: `Stephen King` },
    { text: `Soha nem szabad elfelejtenünk, hogy minden, amit Adolf Hitler tett Németországban »legális« volt, és minden, amit a magyar szabadságharcosok tettek Magyarországon »illegális« volt.`, author: `Martin Luther King` },
    { text: `A rosszkor kelt szóbeszéd, ha egyszer megindul, (...) veszedelmes.`, author: `A Gyűrű szövetsége, Második könyv, 2. fejezet` },
    { text: `Sötétséget sötétséggel elűzni nem lehet, csak a fény teheti azt. A gyűlöletet nem űzi ki a gyűlölet, csak a szeretet teheti azt.`, author: `Martin Luther King` },
    { text: `Sohase fojts vissza, ne hallgass el magad előtt semmit, ami a saját gondolatod ellenében gondolható!`, author: `Friedrich Nietzsche` },
    { text: `Álmodj, amit csak akarsz, menj, ahova szeretnél, légy az, aki szeretnél, mert csak egy életed van, s csak egy lehetőséged, hogy olyan dolgokat csinálj, amit szeretnél!`, author: `Paulo Coelho` },
    { text: `Ha találkozol valakivel egy másik bolygóról, és az a bal kezét nyújtja feléd, meg ne fogd. Lehet, hogy antianyagból van, és mindketten egy hatalmas fényfelvillanás kíséretében eltűntök.`, author: `Stephen Hawking` },
    { text: `Előtted a küzdés, előtted a pálya,\nAz erőtlen csügged, az erős megállja.\nÉs tudod: az erő micsoda? - Akarat,\nMely előbb vagy utóbb, de borostyánt arat`, author: `Arany János` },
    { text: `Van úgy, hogy találkozunk valakivel, talán sose láttuk addig, de alighogy rápillantunk, érdekel, mielőtt egy szót is váltottunk volna.`, author: `Dosztojevszkij` },
    { text: `A dolgokat mindig nevükön kell nevezni. Ha félsz a névtől, félni fogsz magától a dologtól is.`, author: `Joanne Kathleen Rowling` },
    { text: 'Az igazi dicsőség az, ha valaki felül tud emelkedni önmagán.', author: 'Bonaparte Napóleon'},
    { text: `Semmi nincs a világon, ami teljesen rossz lenne (...). Még egy álló óra is pontos napjában kétszer.`, author: `Paulo Coelho` },
    { text: `A legnagyobb történések nem életünk leghangosabb, hanem annak legcsöndesebb órái.`, author: `Friedrich Nietzsche` },
    { text: `A szerelmet nem a férfi és nem a nő akarja, hanem az a hatalmas harmadik, aki nincs, de lenni akar.`, author: `Arthur Schopenhauer` },
    { text: `Mindig csókoljon, egyformán szeressen:\nKönnyben, piszokban, szenvedésben, szennyben.\nAmiben minden álmom semmivé lett,\nHozza vissza Ő: legyen Ő az Élet.`, author: `Ady Endre` },
    { text: `Ha mindnyájan megtennénk, amire képesek vagyunk, szó szerint saját magunkat is elkápráztatnánk.`, author: `Thomas Alva Edison` },
    { text: `Nincsen út járatlan és nincs az a cél, amelyhez ne vezetne ösvény.`, author: `Boncza Berta` },
    { text: `Amikor végtelenből végtelent vonunk le, a válasz bármi lehet.`, author: `Stephen Hawking` },
    { text: `A valóság merő illúzió, bár elég makacsul tartja magát.`, author: `Albert Einstein` },
    { text: `A nevetést nem lehet elutasítani. Ha jön, lehuppan a kedvenc fotelodba, és addig marad ott, ameddig akar.`, author: `Stephen King` },
    { text: `Mi a féltékenység? Szerelem vagy gyűlölet? Szerelemből fakad, de gyűlöletet ébreszt.`, author: `Euripidész` },
    { text: `Szedd össze a bátorságodat, (...) annál nagyobb segítséget senkitől sem kaphatsz.`, author: `Gyűrűk ura` },
    { text: 'Jó, ha az embert emlékeztetik rá, hogy a legerősebb is elgyöngülhet, és a legbölcsebb is tévedhet.', author: 'Gandhi' },
    { text: `A szív nem emlékezni vágyik.`, author: `A gyűrű szövetsége, 564. oldal` },
    { text: `Mit bánom én, ha utcasarkok rongya,\nDe elkisérjen egész a siromba.`, author: `Ady Endre` },
    { text: `Csak a lúzerek, az örök vesztesek hivalkodnak az IQ-jukkal.`, author: `Stephen Hawking` },
    { text: `Az idő igaz,\nS eldönti, ami nem az.`, author: `Petőfi Sándor` },
    { text: `Legkülömb ember, aki bátor\nS csak egy külömb van, aki: bátrabb.`, author: `Ady Endre` },
    { text: `A lángész 1 % ihlet és 99 % verejték.`, author: `Thomas Alva Edison` },
    { text: `Úgy is azonosíthatunk egy pontot, hogy megadjuk a földrajzi hosszúságát, szélességét és a tengerszint feletti magasságát. Szabadon használhatunk három alkalmas koordinátát, bár figyelembe kell vennünk, hogy értelmezési tartományuk korlátozott. Senki se jellemezné a Hold helyzetét a Piccadilly Circustól északra és nyugatra mért távolságával és tengerszint feletti magasságával.`, author: `Stephen Hawking` },
    { text: `A hiedelmeid határozzák meg a gondolataidat, a gondolataid határozzák meg a szavaidat, a szavaid határozzák meg a tetteidet, a tetteid határozzák meg a szokásaidat, a szokásaid határozzák meg az értékeidet, az értékeid határozzák meg a sorsodat.`, author: `Gandhi` },
    { text: `Mulass, igyál s a mai napot mindig is tartsd magadénak, mert sorsé a többi nap.`, author: `Euripidész` },
    { text: `Ahol csődöt mond az akarat, ott magától nyílik meg az út.`, author: `Gyűrűk ura (3. fejezet: A rohani seregszemle)` },
    { text: `Ha szeretünk, az egész embert szeretjük, amilyen, nem amilyennek akarom, hogy legyen.`, author: `Lev Tolsztoj` },
    { text: `Ha meglegyint a közeli halál szele, akkor rájössz, hogy érdemes élni, és sok mindent meg akarsz még tenni az életben.`, author: `Stephen Hawking` },
    { text: `Nem szeretném előre látni a jövőt. Csupán a jelennel törődök. Isten nem adott hatalmat a következő pillanat felett.`, author: `Gandhi` },
    { text: `A kedvesség az a nyelv, amelyen a süket hallani tud, a vak pedig látni.`, author: `Mark Twain` },
    { text: `Tudom, hogy semmit sem tudok.`, author: `Szókratész` },
    { text: `Talán nincs is olyan, hogy jó barát meg rossz barát - talán csak barátok vannak, olyanok, akik az ember mellett állnak, ha megsérül, és akik segítenek, hogy ne legyen olyan magányos. Talán értük mindig érdemes aggódni, reménykedni, őértük érdemes élni. Talán még meghalni is, ha úgy kell lennie. Nincsenek jó barátok. Nincsenek rossz barátok. Csak olyan emberek, akik házat építenek a szívedben.`, author: `Stephen King` },
    { text: `Az emberek könnyebben bocsátanak meg annak, aki téved, mint annak, akinek igaza van.`, author: `Joanne Kathleen Rowling` },
    { text: `Az erő nem testi képességből fakad. Forrása a rendíthetetlen akarat.`, author: `Gandhi` },
    { text: `Énszerintem aki jól beszél, de rosszul cselekszik, még bűnösebb, mint más, mert azt reméli, hogy sima szavakkal ügyesen elsimítja a gonosztettet, és így nem riad vissza semmitől.`, author: `Euripidész` },
    { text: `Az ember még csak nem is sejti, nemhogy előre tudná, mi az, ami megpróbáltatásain át fogja segíteni.`, author: `Gandhi` },
    { text: `A hideg elfordulás, a közöny a nyílt ellenszenvnél is veszedelmesebb méreg.`, author: `Joanne Kathleen Rowling` },
    { text: `Még a legagyafúrtabb póknak a hálójában is akadhat egy-egy gyönge szál.`, author: `A Gyűrű szövetsége, Második könyv, 2. fejezet` },
    { text: `S néki, míg a sír rá nem lehell,\nMindig tűrni és remélni kell!`, author: `Arany János` },
    { text: `Bár nekünk, emberi lényeknek fizikai korlátaink vannak, szellemünk szabadon bejárhatja az egész világmindenséget.`, author: `Stephen Hawking` },
    { text: `A legfontosabb találkozásokat a lelkek előre megbeszélik egymással, amikor a testek még nem is látták egymást.`, author: `Paulo Coetho` },
    { text: `Az úton végig kell menni, jóllehet nagyon keserves. És sem erővel, sem bölcsességgel nem jutunk messze rajta. Az utat éppoly reménnyel keresheti a gyönge, mint az erős. Nem ritkaság, hogy ez a tettek sora, amelyek a világ kerekét igazgatják: kis kezek hajtják végre, mert közben a nagyok szeme másfelé tekint.`, author: `Gyűrűk ura` },
    { text: `Szabadságot szenvedés nélkül nem lehet kivívni.`, author: `Gandhi` },
    { text: `A csoda egy kivétel a törvények alól, ezért ahol nincsenek törvények, ott kivételek, azaz csodák sem létezhetnek.`, author: `Albert Einstein` },
    { text: `Úgy érzem, veled még az öregséget is elviselném.`, author: `Stephen King` },
    { text: `A világon két dolog végtelen: a világegyetem és az emberi hülyeség. Bár az elsőben nem vagyok biztos.`, author: `Albert Einstein` },
    { text: `A szeretetben mindig van valamennyi őrület. De az őrületben is mindig van valamennyi ész.`, author: `Friedrich Nietzsche` },
    { text: `Az vagyok, aki vagyok. Úgyse lehetek más: mért féljek hát fölfödözni, ki vagyok?`, author: `Szophoklész` },
    { text: `Minden értelmes ember önfejűnek tűnik időnként.`, author: `Stephen Hawking` },
    { text: `A szerelem a világ leghatalmasabb ereje, amely a leginkább emberi.`, author: `Gandhi` },
    { text: `Emberek vagyunk, tudnunk kell elviselni a sors csapásait.`, author: `Euripidész` },
    { text: `Az idő, amit a rózsádra vesztegettél: az teszi olyan fontossá a rózsádat.`, author: `Antoine de Saint-Exupéry: A kis herceg` },
    { text: `Aki boldogtalan nem volt, nem tudja megbecsülni boldogságát.`, author: `Petőfi Sándor` },
    { text: `Ha megharagszol a kritikusra, szinte biztosra veheted, hogy igaza van.`, author: `Stephen King` },
    { text: `Nem akarok harcolni. De ölbe tett kézzel várni az elkerülhetetlent még rosszabb.`, author: `Gyűrűk ura` },
    { text: `Sajátságos dolog, hogy az utánzókat éppen az utánozhatatlan egyéniségek vonzzák legjobban.`, author: `Babits Mihály` },
    { text: `A csendes embereknek vannak a leghangosabb gondolataik.`, author: `Stephen Hawking` },
    { text: `A remény jó dolog, talán a legjobb. És a jó dolgok nem halnak meg, miként a rosszak sem élnek örökké.`, author: `Stephen King` },
    { text: `Sok ellenséggel fogtok találkozni, nyílt ellenséggel és álruhással, ám meglehet, épp ott találtok jó barátra, ahol legkevésbé számíttok rá.`, author: `A Gyűrű szövetsége, Második könyv, 3. fejezet` },
    { text: `Nem fogok dühöngeni: filozofálni fogok. Ebben az országban annyira úr a hülyeség, hogy itt már csak filozofálni lehet.`, author: `Ady Endre` },
    { text: `Vesd el a sajnálkozást és a félelmet! Tedd azt, amit éppen tenned kell.`, author: `Gyűrűk ura` },
    { text: `Aki még sosem követett el hibát, valószínűleg még sosem próbált semmi új dolgot.`, author: `Albert Einstein` },
    { text: `Az embert társas lénnyé leginkább az teszi, hogy képtelen a magányt és ebben önmagát elviselni. Belső üressége és az unalom hajtja társaságba, űzi idegenbe, utazásra.`, author: `Arthur Schopenhauer` },
    { text: `Az egészség nem minden, de az egészség nélkül minden semmi.`, author: `Arthur Schopenhauer` },
    { text: `Szeretetre születtem, s nem gyűlöletre.`, author: `Szophoklész` },
    { text: `Vannak dolgok, melyeket jobb nem látni, és vannak dolgok, melyeket jobb elveszíteni, mint megtalálni.`, author: `Stephen King` },
    { text: `Csak aki begyakorolta az egyedüllétet, az tud kettesben élni mással.`, author: `Euripidész` },
    { text: `Van egy szó, amely az élet minden terhétől és fájdalmától megszabadít bennünket: ez a szó a szerelem.`, author: `Szophoklész` },
    { text: `Boldogság az, ha amit gondolsz, amit mondasz, és amit teszel, összhangban vannak egymással.`, author: `Gandhi` },
    { text: `Kétféle hatalom létezik. Az egyik a büntetéstől való félelemmel éri el a célját, a másik szeretetteljes cselekedetekkel. Az szereteten alapuló hatalom százszorta hatékonyabb és maradandóbb, mint az, amelyik a büntetéstől való félelemből ered.`, author: `Gandhi` },
    { text: `Ritkán gondolunk arra, amink van, és túl gyakran arra, amink nincs. Ez a magatartás több nyomorúságot okozott már az emberiségnek, mint az összes háború és járvány együttvéve.`, author: `Arthur Schopenhauer` },
    { text: `Aki nem elégedett azzal, amije van, nem lenne elégedett azzal sem, amire vágyakozik.`, author: `Szókratész` },
    { text: `A fizika kicsit más, mint az orvosok világa. A fizikában nem számít, melyik iskolába jártál vagy kinek vagy a rokona. Csak az számít, amit megcsinálsz.`, author: `Stephen Hawking` },
    { text: `Álljon előmbe izzó, forró nyárban:\n'Téged szeretlek, Te vagy, akit vártam.'`, author: `Ady Endre` },
    { text: `Más a szándék és más a tett.`, author: `A két torony, 909. oldal` },
    { text: `Nem buktam el, csak találtam tízezer utat, ami nem járható.`, author: `Thomas Alva Edison` },
    { text: `Semmit nem lehet megtanítani egy embernek. Csak segíteni benne, hogy rátaláljon önmagán belül.`, author: `Galileo Galilei` },
    { text: `Az ostoba azért él, hogy egyék és igyék, az okos azért eszik és iszik, hogy éljen.`, author: `Szókratész` },
    { text: 'Sose búsúlj! úgyis késő;\nAmi elmúlt, vissza nem jő.', author: `Petőfi Sándor` },
    { text: `Mindenik embernek a lelkében dal van\nés a saját lelkét hallja minden dalban.\nÉs akinek szép a lelkében az ének,\naz hallja a mások énekét is szépnek.`, author: `Babits Mihály` },
    { text: `A bölcs emberek azért beszélnek, mert van mondanivalójuk; a bolondok azért, mert mondaniuk kell valamit.`, author: `Platón` },
    { text: `Van a világon egy szív, melynek dobbanása egy az enyémmel.`, author: `Ady Endre` },
    { text: `Az élet már adott sokat,\nBódítót, furcsát és keservest,\nDe még valamit tartogat`, author: `Ady Endre` },
    { text: `Az élet százszor rövidebb annál, hogy unatkozhassunk.`, author: `Friedrich Nietzsche` },
    { text: `Nincs szebb dolog ezen a földön az eleve eldöntött harmóniánál, sem pedig a lelkes anyag és a telítettség fogalmánál.`, author: `Voltaire` },
    { text: `Az előítélet nem egyéb, mint vélemény ítélet nélkül. A gyermekeknek az egész világon olyan véleményeket sugallnak, amilyeneket csak akarnak, s előbb, mintsem a gyermek képes volna ítélkezni.`, author: `Voltaire` },
    { text: `Igazából nem is kéne itt lennünk! De itt vagyunk. Olyan ez, mint a nagy regényekben, Frodó úr, amikre mindenki emlékszik. Mind teli voltak sötétséggel és veszéllyel, és néha még a végüket sem akartuk tudni, mert boldogan semmiképpen sem végződhettek. Hogy lehetne a világ újra olyan, mint volt, ha ennyi szörnyűség történt közben? De végül is ez csak egy múló dolog. Ez a sötétség. Még a sötétségnek is el kell múlnia, új nap virrad majd fel! És ha egyszer kisüt a nap, annál tisztábban fog ragyogni. Az ember azokra a történetekre emlékszik, amik jelentettek valamit, még ha túl kicsi is volt hozzá, hogy megértse, miért. De azt hiszem, Frodó úr, én igenis értem, most már tudom! E történetek szereplői gyakran visszafordulhattak volna, de nem tették.\nTovábbmentek, mert volt mibe kapaszkodniuk. (...) Akad még jó ebben a világban, Frodó úr, amiért érdemes küzdeni.`, author: `Gyűrűk ura` },
    { text: `Úgy tűnik, sokkal nehezebb legyőzni a láthatatlan szenvedélyeket, mint fegyverrel meghódítani a látható világot.`, author: `Gandhi` },
    { text: `Úgy tarthatunk meg valamit, ahogyan megszereztük.`, author: `Gandhi ` },
    { text: `Más fog parancsolni annak, ki önmagának engedelmeskedni képtelen.`, author: `Friedrich Nietzsche` },
    { text: `Gyakran csak évek múlva látjuk helyes világításban mások cselekedeteit, sőt néha a magunkéit is.`, author: `Arthur Schopenhauer` },
    { text: `Sok mindent elfelejtettem, amiről azt hittem, hogy tudom, és sok mindent megtanultam, amit már elfelejtettem. Sok mindent látok, ami messze van, és sok mindent nem, ami itt van a szemem előtt.`, author: `Gyűrűk ura` },
    { text: `A legbonyolultabb, s ezért a legértékesebb tulajdonság a döntésképesség`, author: `Bonaparte Napóleon` },
    { text: `Ha be akarsz pillantani az emberek lelkébe és meg akarsz ismerni valakit, ne azt figyeld, hogyan beszél, hallgat, sír, vagy hogy megmozgatják-e a nemes eszmék, hanem azt, hogyan nevet. Aki szívből tud kacagni, jó ember.`, author: `Dosztojevszkij` },
    { text: `Van, amibe jobb belevágni, mint visszautasítani, még ha rossz véget ér is.`, author: `Gyűrűk ura` },
    { text: `- Gondolja (...), hogy az emberek mindig úgy öldökölték egymást, mint ma? Hogy mindenkor hazugok, bitangok, csalfák, hálátlanok, rablók, gyengék, állhatatlanok, gyávák, irigyek, falánkok, részegesek, fösvények, becsvágyók, vérengzők, rágalmazók, kicsapongók, elvakultak, álszentek és ostobák voltak?\n- Mit gondol (...), ettek-e mindig karvalyok galambot, ha foghattak egyet?\n- Hogyne, biztosan (...).\n- Hát akkor (...), ha ugye a karvalyoknak mindig egyforma volt a természetük, mért gondolja, hogy az ember megváltoztatta a magáét?`, author: `Voltaire` },
    { text: `Mi a jobb, ha hazád királyság, vagy ha köztársaság? Négyezer esztendeje vitatkoznak erről az emberek. Kérdezd meg a gazdagokat, melyik a jobb: valamennyien az arisztokrácia mellett foglalnak állást, kérdezd meg a népet: a demokráciát választja, a királyságot kizárólag a királyok részesítik előnyben. Hogyan lehetséges hát, hogy csaknem az egész világon mégis királyok uralkodnak? (...) Az igazi ok az, mint többen is kimutatták, hogy az emberek nagyon ritkán méltók rá, hogy maguk kormányozzák magukat.`, author: `Euripidész` },
    { text: `Azt a legnehezebb befejezni, amit el sem kezdesz.`, author: `Gyűrűk ura` },
    { text: `Azzal az idővel kell foglalkoznunk, ami megadatik nekünk.`, author: `Gyűrűk ura` },
    { text: `Csak amikor elég sötét van, látod meg a csillagokat.`, author: `Martin Luther King` },
    { text: `Hiszen ki nem talál\nAz életben többé gyönyört, úgy gondolom, Nem élő ember az, csak élő holttetem. Hiába rakod házad kincsekkel tele, Hiába vagy király, ha már örülni sem Tudsz semminek. Ha érte boldogságodat Kell adni, minden más a füst árnyéka csak.`, author: `Szophoklész` },
    { text: `A nevetést nem lehet elutasítani. Ha jön, lehuppan a kedvenc fotelodba, és addig marad ott, ameddig akar.`, author: `Stephen King` },
    { text: `Fájdalmasan tudatában vagyok tökéletlenségeimnek, s ebben a megismerésben rejlik minden erőm.`, author: `Gandhi` },
    { text: `Soha nem szabad elfelejtenünk, hogy minden, amit Adolf Hitler tett Németországban »legális« volt, és minden, amit a magyar szabadságharcosok tettek Magyarországon »illegális« volt.`, author: `Martin Luther King` },
    { text: `A képzelet sokkal fontosabb, mint a tudás. A tudás véges. A képzelet felöleli az egész világot.`, author: `Albert Einstein` },
    { text: `Ha egy ember semmit sem talál, amiért meg tudna halni, akkor élnie sem érdemes.`, author: `Martin Luther King` },
    { text: `Az emberi vonás, amin a leginkább változtatnék, az agresszió. A barlanglakó ősemberek korában ez előnyt adhatott a túléléshez, a több élelem, élettér vagy egy társ megszerzéséhez, akivel utódot lehetett nemzeni, de manapság félő, hogy mindannyiunkat elpusztít.`, author: `Stephen Hawking` },
    { text: `Senkinek nem engedem, hogy a koszos lábával átgyalogoljon az elmémen.`, author: `Gandhi` },
    { text: `Őrült, aki halni vágy, még a rút élet is szebb, mint a szép halál.`, author: `Euripidész` },
    { text: `Nem szabad elfelejtenünk, hogy a történelem során mindig is voltak olyan zsarnokok és gyilkosok, akik egy ideig legyőzhetetlennek tűntek, de végül mindig elbuktak. Mindig.`, author: `Gandhi` },
    { text: `Az idealista javíthatatlan. Ha kipenderítik a mennyországból, eszményt kovácsol a poklából.`, author: `Friedrich Nietzsche` },
    { text: `Az elme számol, a lélek sóvárog, a szív pedig tudja, amit tud.`, author: `Stephen King` },
    { text: `Mindenkitől azt kell követelni, amit az illető megtehet. A tekintély legelső alapja az értelem (...). Ha népednek azt parancsolod, vesse magát a tengerbe: föllázad, forradalmat csinál. Azért van jogom engedelmességet követelni, mert ésszerűek a parancsaim.`, author: `Antoine de Saint-Exupéry: A kis herceg` },
    { text: `Képzelj magad elé egy magányos bölcset, amint egy sötét úton sétál végig pirkadat előtt, és a kezében tartott lámpással utat mutat embertársainak! Az efféle bölcsek, a világosság hordozói csak azt az utat mutathatják meg neked, amelyet hajlandó vagy követni. Ha letérnek az útról, követőik is irányt tévesztenek. Ha te lennél ez a bölcs, vajon képes lennél-e példáddal utat mutatni az embereknek?`, author: `Gandhi` },
    { text: `Egész életünkön keresztül mindig csak a jelent birtokoljuk és sohasem többet. A különbség csak az, hogy eleinte hosszú jövőt látunk magunk előtt, a vége felé pedig hosszú múltat magunk mögött.`, author: `Arthur Schopenhauer` },
    { text: `Mindenki bölcsebb, hogyha másoknak baját kell megítélni, mint a saját ügyét.`, author: `Euripidész` },
    { text: `Nem azért dolgozott- e az elmúlt nyolc évben a társadalom, hogy soha többé ne legyen olyan kormányfője Magyarországnak, aki nyugodtan kijelentheti: rajta kiνάl nincs mάs alternatíva. Aki ezt állítja, az nem kormányozni, hanem uralkodni akar.`, author: `Orbán Viktor` },
    { text: `Bizonyos (...) s kimutatható, hogy nem is lehetnek másképp a dolgok, mert ha már mindennek célja van, minden, ugyebár, szükségképpen a legeslegjobb célért is van. Orrunk például azért van, hogy legyen min hordani a szemüveget, s lám ezért is hordunk szemüveget. Lábunk láthatólag arra való, hogy nadrágot húzzunk rá, ezért is van nadrágunk. A kövek arra termettek, hogy szépen megfaragjuk őket, no meg persze, hogy kastélyokat építsenek belőlük.`, author: `Voltaire ` },
    { text: `A gyenge nem tud megbocsátani. A megbocsátás az erősek tulajdonsága`, author: `Gandhi` },
    { text: `Ha mindent megtettél, amire képességeidből telik, ember vagy. Ha mindent megtettél, amit akartál, akkor isten.`, author: `Bonaparte Napóleon` },
    { text: `Még ha tudnám is, hogy holnap a világ darabokra hullik, akkor is elültetném az almafámat.`, author: `Martin Luther King` },
    { text: `A világ erőforrásai elegendőek ahhoz, hogy kielégítsék mindenki szükségleteit, de nem elegendőek ahhoz, hogy kielégítsék mindenki mohóságát.`, author: `Gandhi` },
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: `Április 1. Ez az a nap, amelyen emlékezetünkbe idéztetik, hogy micsodák vagyunk az évnek többi háromszázhatvannégy napján.`, author: `Mark Twain` },
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
    { text: '', author: ''},
];



function showQuote(index) {
    const quote = quotes[index] || { text: "Még nincs idézet.", author: "" };
    document.getElementById("quoteText").innerText = `"${quote.text}"`;
    document.getElementById("quoteAuthor").innerText = `– ${quote.author}`;
    const box = document.getElementById("quoteBox");
    box.classList.add("visible");
    box.classList.remove("hidden");
}


document.getElementById("showQuote").addEventListener("click", () => {
    showQuote(daysSinceWedding - 1);
});


const timeline = document.getElementById("timeline");
for (let i = 1; i <= quotes.length; i++) {
    const btn = document.createElement("button");
    btn.innerText = `${i}. nap`;
    if (i <= daysSinceWedding) {
        btn.addEventListener("click", () => showQuote(i - 1));
    } else {
        btn.classList.add("disabled");
        btn.disabled = true;
    }
    timeline.appendChild(btn);
}
